name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the action on merge
      - main_my_own_aws

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Assume AWS Role using OIDC
        id: aws-credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin 442387259505.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build and tag Docker image
        run: |
          docker build -t atm .
          docker tag atm:latest 442387259505.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/learn/atm:latest

      - name: Push Docker image to ECR
        run: |
          docker push 442387259505.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/learn/atm:latest