name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the action on merge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        run: |
          aws --version
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build JAR using Maven
        run: mvn clean package

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 442387259505.dkr.ecr.ap-southeast-1.amazonaws.com
          
      - name: Build Docker image
        run: |
          docker build -t learn/atm .
    
      - name: Tag Docker image
        run: |
          docker tag learn/atm:latest 442387259505.dkr.ecr.ap-southeast-1.amazonaws.com/learn/atm:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 442387259505.dkr.ecr.ap-southeast-1.amazonaws.com/learn/atm:latest
