name: Build and Push to ECR

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the action on merge

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::872583825157:role/k8s-developer                          
          aws-region: ap-southeast-1
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 872583825157.dkr.ecr.ap-southeast-1.amazonaws.com
          
      - name: Build, tag, and push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          REPOSITORY_URI=872583825157.dkr.ecr.ap-southeast-1.amazonaws.com/periodictable/atm:latest
          docker build -t $REPOSITORY_URI:$IMAGE_TAG .
          docker push $REPOSITORY_URI:$IMAGE_TAG
